# Explanation of the new data available

### Link of the data:
- https://opendata-ajuntament.barcelona.cat/data/en/dataset/trams-aparcament-superficie
- https://opendata-ajuntament.barcelona.cat/data/ca/dataset/colors-aparcaments-superficie
- https://opendata-ajuntament.barcelona.cat/data/ca/dataset/tarifes-aparcament-superficie
- https://opendata-ajuntament.barcelona.cat/data/ca/dataset/horaris-aparcaments-superficie
- https://opendata-ajuntament.barcelona.cat/data/ca/dataset/transit-relacio-trams

1) TRAMS
- ID_TRAM: Unique identifier of the parking area.
- UTM_IX: UTM coordinate of the initial position along the X axis.
- UTM_FX: UTM coordinate of the final position along the X axis.
- UTM_IY: UTM coordinate of the initial position along the Y axis.
- UTM_FY: UTM coordinate of the final position along the Y axis.
- LATITUD_I: Latitude of the starting position.
- LONGITUD_I: Longitude of the initial position.
- LATITUD_F: Latitude of the final position.
- LONGITUD_F: Longitude of the final position.
- ID_TARIFA: Identifier of the tariff associated with the parking section.
- ID_HORARIO: Identifier of the time associated with the parking section.
- ID_TARIFA1: Alternative identifier of the tariff associated with the parking section.
- ID_HORARIO1: Alternative identifier of the time associated with the parking section.
- TIPUS_TRAM: Type of parking section.
- ADREÇA: Address of the parking area.
- COLOR_RGB: Color of the parking area in RGB format.
- PLACES: Number of parking spaces available in the parking area.

2) COLORS
- COLORS: Name of the color of the parking area.
- pCOLOR: Color code associated with the parking area.
- RGB: RGB value of the color of the parking area.

3) HORARIS
- ID_HORARI: Time identifier.
- CODI_HORARI: Time code.
- DESCRIPTION: Description of the time.
- DESC_CURTA: Brief description of the time.
- INCLUS_FESTIUS: Flag indicating whether holidays are included in the timetable.
- PARQUING_SOLS_DINS_HORARI: Flag indicating whether parking is allowed only during the specified hours.

4) TARIFES
- TARIFA_ID: Tariff identifier.
- ID_TIPUS_CONFIGURACIO: Tariff configuration type identifier.
- ID_TIPUS_TARIFA: Tariff type identifier.
- CODI_TARIFA: Tariff code.
- TIPUS_FRACCIO: Type of fare fraction.
- TEMPS_MAXIM: Maximum time allowed for the rate.
- TEMPS_MINIM: Minimum time allowed for the rate.
- DESCRIPTION: Description of the tariff.
- DESC_CURTA: Brief description of the rate.
- IMPORT_FRACCIO: Amount of the fraction of the fare.
- IMPORT_MAXIM: Maximum amount of the fee.

1) TRAMS:  
Provides detailed information on paid parking sections in Barcelona.  
Each row of the dataset represents a single parking lot.  
Columns:  
- ID_TRAM: Unique identifier of the parking area.
- UTM Coordinates and Latitude/Longitude: These columns provide spatial coordinates in different formats for the starting and ending location of the parking lot.
- ID_TARIFA and ID_TARIFA1: Identifiers of the tariffs associated with the parking section.
- ID_HORARIO and ID_HORARIO1: Identifiers of the times associated with the parking section.
- TIPUS_TRAM: Type of parking section.
- ADREÇA: Address of the parking area.
- COLOR_RGB: Color of the parking area in RGB format.
- PLACES: Number of parking spaces available in the parking area.

2) COLORS:  
Contains information on the colors associated with different parking types, along with their RGB codes.  
Columns:  
- COLORS: Name of the color of the parking area.
- pCOLOR: Color code associated with the parking area.
- RGB: RGB value of the color of the parking area.

3) HORARIS:  
Provides details on the operating hours of paid car parks.  
Columns:  
- ID_HORARI: Time identifier.
- CODI_HORARI: Time code.
- DESCRIPTION: Description of the time.
- DESC_CURTA: Brief description of the time.
- INCLUS_FESTIUS: Flag indicating whether holidays are included in the timetable.
- PARQUING_SOLS_DINS_HORARI: Flag indicating whether parking is allowed only during the specified hours.

4) TARIFES:  
Lists the rates associated with paid parking.  
Columns:  
- TARIFA_ID: Tariff identifier.
- ID_TIPUS_CONFIGURACIO: Tariff configuration type identifier.
- ID_TIPUS_TARIFA: Tariff type identifier.
- CODI_TARIFA: Tariff code.
- TIPUS_FRACCIO: Type of fare fraction.
- TEMPS_MAXIM: Maximum time allowed for the rate.
- TEMPS_MINIM: Minimum time allowed for the rate.
- DESCRIPTION: Description of the tariff.
- DESC_CURTA: Brief description of the rate.
- IMPORT_FRACCIO: Amount of the fraction of the fare.
- IMPORT_MAXIM: Maximum amount of the fee.

The column COLORS in the COLORS.csv dataset:    
- AZL (Àrea Blava): paid parking area or a blue zone, where payment for parking is required.
- VR (Area Residents): Parking area reserved for residents, where special rules or reduced rates may apply for those living in the area.
- VM (Àrea Verda): green area, which could be a free parking area or an area with less strict parking restrictions than other areas.
- BUS (Zona autobús): parking area reserved for buses or other forms of public transport.
- DUM (Zona Distribució urban de mercaderies): area dedicated to the urban distribution of goods, for example a loading and unloading area for commercial vehicles.

In [2]:
import pandas as pd

In [27]:
df_trams = pd.read_csv('TRAMS.csv')
df_trams

,ID_TRAM,UTM_IX,UTM_FX,UTM_IY,UTM_FY,LATITUD_I,LONGITUD_I,LATITUD_F,LONGITUD_F,ID_TARIFA,ID_HORARIO,ID_TARIFA1,ID_HORARIO1,TIPUS_TRAM,ADREÇA,COLOR_RGB,PLACES
0,7,431371.206,431359.176,4582803.652,4582803.655,41.393835,2.179069,41.393834,2.178925,46,82,NaN,82,AZL,"ROGER DE FLOR, 79, C",0000FF,5.0
1,8,431322.330,431311.483,4582399.137,4582420.894,41.390188,2.178531,41.390383,2.178398,52,104,NaN,104,VR,"LLUIS EL PIADOS, 9 , C",008000,10.0
2,13,431288.758,431273.443,4582305.752,4582322.247,41.389344,2.178140,41.389491,2.177955,46,81,NaN,81,AZL,"MENDEZ NUÑEZ, 9, C",0000FF,10.0
3,14,431301.693,431288.550,4582318.450,4582330.947,41.389459,2.178293,41.389571,2.178134,46,81,NaN,81,AZL,"MENDEZ NUÑEZ, 4, C",0000FF,3.0
4,19,431498.403,431489.250,4582755.634,4582746.776,41.393414,2.180596,41.393333,2.180488,54,13,52.0,13,VM,"ALI BEI, 42, C",00FF00,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17342,99912164,428832.707,428841.239,4580164.027,4580178.532,41.369841,2.149019,41.369972,2.149119,69,77,NaN,77,BUS,"FRANCESC FERRER GUARDIA, 29, SECTOR B2 , AV",00FFFF,30.0
17343,99912164,428842.139,428849.415,4580180.292,4580202.322,41.369988,2.149130,41.370187,2.149214,69,77,NaN,77,BUS,"FRANCESC FERRER GUARDIA, 29, SECTOR B2 , AV",00FFFF,30.0
17344,99912164,428848.994,428855.005,4580204.536,4580233.208,41.370207,2.149209,41.370466,2.149278,69,77,NaN,77,BUS,"FRANCESC FERRER GUARDIA, 29, SECTOR B2 , AV",00FFFF,30.0
17345,99912164,428854.584,428858.820,4580235.421,4580263.226,41.370486,2.149272,41.370737,2.149320,69,77,NaN,77,BUS,"FRANCESC FERRER GUARDIA, 29, SECTOR B2 , AV",00FFFF,30.0
17346,99912164,428859.720,428860.711,4580264.985,4580276.467,41.370753,2.149330,41.370856,2.149341,69,77,NaN,77,BUS,"FRANCESC FERRER GUARDIA, 29, SECTOR B2 , AV",00FFFF,30.0

In [28]:
df_trams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17347 entries, 0 to 17346
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_TRAM      17347 non-null  int64
 1   UTM_IX       17347 non-null  float64
 2   UTM_FX       17347 non-null  float64
 3   UTM_IY       17347 non-null  float64
 4   UTM_FY       17347 non-null  float64
 5   LATITUD_I    17347 non-null  float64
 6   LONGITUD_I   17347 non-null  float64
 7   LATITUD_F    17347 non-null  float64
 8   LONGITUD_F   17347 non-null  float64
 9   ID_TARIFA    17347 non-null  int64
 10  ID_HORARIO   17347 non-null  int64
 11  ID_TARIFA1   11799 non-null  float64
 12  ID_HORARIO1  17347 non-null  int64
 13  TIPUS_TRAM   17347 non-null  object
 14  ADREÇA       17343 non-null  object
 15  COLOR_RGB    17347 non-null  object
 16  PLACES       17329 non-null  float64
dtypes: float64(10), int64(4), object(3)
memory usage: 2.3+ MB

In [29]:
df_colors = pd.read_csv('COLORS.csv')
df_colors

  COLORS  pCOLOR     RGB
0    AZL       1  0000FF
1     VR       2  FFFFFF
2     VM       3  00FF00
3    BUS       4  000080
4    DUM       7  FFA420

In [30]:
df_colors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   COLORS  5 non-null      object
 1   pCOLOR  5 non-null      int64
 2   RGB     5 non-null      object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes

In [31]:
df_horaris = pd.read_csv('HORARIS.csv')
df_horaris

,ID_HORARI,CODI_HORARI,DESCRIPCIO,DESC_CURTA,INCLUS_FESTIUS,PARQUING_SOLS_DINS_HORARI
0,1,H1,de Dl a Ds de 09:00 a 14:00 i de 16:00 a 20:00,de Dl a Ds 9-14 i 16-20,0,0
1,2,H2,de Dl a Dv de 09:00 a 14:00 i de 16:00 a 20:00,de Dl a Dv 9-14 i 16-20,0,0
2,3,H3,de Dl a Dv de 09:00 a 14:00 i de 16:00 a 20:0...,de Dl a Dv 9-14 i 16-20 Ds 9-14,0,0
3,6,H6,de Dl a Dv de 09:00 a 14:00,de Dl a Dv 9-14,0,0
4,7,H7,de Dl a Dv de 09:30 a 14:00 i de 16:30 a 20:00,de Dl a Dv 9:30-14 i 16:30-20,0,0
...,...,...,...,...,...,...
90,109,Z56,de Dl a Dv de 10:00 a 17:000,de Dl a Dv 10-17,0,1
91,110,Z57,de Dl a Ds de 07:00 a 11:00 i de 14:00 a 16:30,de Dl a Ds 7-11 i 14-16:30,0,1
92,9999,FUT,de Dl a Dv de 09:30 a 13:00,de Dl a Dv de 09:30 a 13:00,0,0
93,99999888,H99,de Dl a Dv de 14:00 a 20:00,de Dl a Dv de 14-20,0,1
94,99999999,Z99,de Dl a Dv de 08:00 a 14:00,de Dl a Dv de 8-14,0,1

In [32]:
df_horaris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_HORARI                  95 non-null     int64
 1   CODI_HORARI                95 non-null     object
 2   DESCRIPCIO                 95 non-null     object
 3   DESC_CURTA                 95 non-null     object
 4   INCLUS_FESTIUS             95 non-null     int64
 5   PARQUING_SOLS_DINS_HORARI  95 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.6+ KB

In [33]:
df_tarifes = pd.read_csv('TARIFES.csv')
df_tarifes

,ID_TARIFA,ID_TIPUS_CONFIGURACIO,ID_TIPUS_TARIFA,CODI_TARIFA,TIPUS_FRACCIO,TEMPS_MAXIM,TEMPS_MINIM,DESCRIPCIO,DESC_CURTA,IMPORT_FRACCIO,IMPORT_MAXIM
0,46,1,1,A,1,2,0,"2,50 euros/hora Temp.max Est. 2 hores","2,50 E/h <= 2h",2.50,5.00
1,47,1,1,B,1,2,0,"2,25 euros/hora Temp.max Est. 2 hores","2,25 E/h <= 2h",2.25,4.50
2,48,1,1,C,1,3,0,"1,96 euros/hora Temp.max Est. 3 hores","1,96 E/h <= 3h",1.96,5.88
3,49,1,1,D,1,4,0,"1,08 euros/hora Temp.max Est. 4 hores","1,08 E/h <= 4h",1.08,4.32
4,52,2,2,RES,2,20,1,"0,20 euros/dia Temp.max Est. 20 dies laborables","0,20 E/d <= 20d",0.20,4.00
5,53,3,3,MA1,1,1,0,"3,00 euros/hora Temp.max Est. 1 hores","3,00 E/h <= 1h",3.00,3.00
6,54,3,3,MA2,1,2,0,"3,00 euros/hora Temp.max Est. 2 hores","3,00 E/h <= 2h",3.00,6.00
7,55,3,3,MB1,1,1,0,"2,75 euros/hora Temp.max Est. 1 hores","2,75 E/h <= 1h",2.75,2.75
8,56,3,3,MB2,1,2,0,"2,75 euros/hora Temp.max Est. 2 hores","2,75 E/h <= 2h",2.75,5.50
9,57,5,5,BU2,1,2,0,"2,45 euros/hora Temp.Max.Est. 2 hores","2,45 E/h <= 2h",2.45,4.90
10,58,7,7,CYD,0,30,0,AREADUM temps.max.Est.30min,0 E/h <= 30min,0.00,0.00
11,59,5,5,BU1,1,2,0,"5,30 euros/hora Temp.Max.Est. 2 hores","5,30 E/h <= 2h",5.30,10.60
12,60,14,14,GRA1,1,1,0,"2,5 euros/hora Temp.max Est. 1 hores","2,5 E/h <= 1",2.50,2.50
13,61,14,14,GRA2,1,2,0,"2,5 euros/hora Temp.max Est. 2 hores","2,5 E/h <= 2",2.50,5.00
14,62,8,8,EDM1,0,10,0,tarifa gratuita durant 10 minuts per encotxame...,E/D 0e <=10min,0.00,0.00
15,63,8,8,EDH1,1,2,0,tarifa gratuita durant 2 hores per encotxament...,E/D 0e <= 2h,0.00,0.00
16,64,5,5,BU3,1,2,0,6 euros/hora Temp.Max.Est. 2 hores,6 E/h <= 2h,6.00,12.00
17,65,5,5,BU4,1,2,0,3 euros/hora Temp.Max.Est. 2 hores,3 E/h <= 2h,3.00,6.00
18,66,5,5,BUA1,1,2,0,6 euros/hora Temp.Max.Est. 2 hores,6 E/h <= 2h,6.00,12.00
19,67,5,5,BUAV,1,2,0,VARIABLE: 6 ó 9 euros/hora Temp.Max.Est. 2 hor...,6 ó 9 E/h <= 2h,6.00,12.00
20,68,5,5,BUB3,1,24,0,3 euros/hora. Sense limit de temps,3 E/h,3.00,72.00
21,69,15,15,BUFM,2,24,0,"20E/Función, 30E/2 funciones","20 E/F, 30 E/2F",20.00,480.00
22,72,5,5,BUB4,1,12,0,4 euros/hora. Sense limit de temps,4 E/h,4.00,48.00
23,73,5,5,BUA2,1,2,0,12 euros/hora. Temp.Max.Est. 2 hores,12 E/h,12.00,24.00
24,74,8,8,EDM2,0,10,0,"tarifa fixa 2,5E durant 10 minuts per encotxam...","E/D 2,5E<=10min",2.50,25.00

In [34]:
df_tarifes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_TARIFA              25 non-null     int64
 1   ID_TIPUS_CONFIGURACIO  25 non-null     int64
 2   ID_TIPUS_TARIFA        25 non-null     int64
 3   CODI_TARIFA            25 non-null     object
 4   TIPUS_FRACCIO          25 non-null     int64
 5   TEMPS_MAXIM            25 non-null     int64
 6   TEMPS_MINIM            25 non-null     int64
 7   DESCRIPCIO             25 non-null     object
 8   DESC_CURTA             25 non-null     object
 9   IMPORT_FRACCIO         25 non-null     float64
 10  IMPORT_MAXIM           25 non-null     float64
dtypes: float64(2), int64(6), object(3)
memory usage: 2.3+ KB

### !!! For the merging and the analysis check the file TRAMS_COLORS_HORARIS_TARIFES.ipynb

## Other parking data:
- Our old dataset, updated to april 2024: https://opendata-ajuntament.barcelona.cat/data/en/dataset/infraestructures-inventari-reserves/resource/93d8128d-417d-44da-87cb-df7420c40641
- (json)  https://opendata-ajuntament.barcelona.cat/data/en/dataset/aparcaments-sota-superficie 
- (json)  https://opendata-ajuntament.barcelona.cat/data/en/dataset/siu-area-blava

https://opendata-ajuntament.barcelona.cat/data/en/dataset/aparcaments-sota-superficie  
This data provides detailed information on parking in Barcelona:

- ParkingList: List of parking entities.
- Parking: List of car parks.
  - ParkingCode: Parking identification code.
  - Name: Name of the car park.
  - Address: Address of the car park.
  - ParkingAccess: List of parking access entities.
    - Access: List of vehicle accesses.
      - AccessID: Access identifier.
      - AccessAddress: Access address.
      - Longitude: Geographic longitude coordinate of the car park access.
      - Latitude: Geographic latitude coordinate of the car park access.
  - MaxWidth: Maximum width of the vehicle in meters.
  - MaxHeight: Maximum height of the vehicle in meters.
  - Guarded: Boolean to indicate whether the car park is guarded.
  - InformationPoint: Boolean to indicate if there is an information point in the car park.
  - Open: Parking opening hours.
  - Close: Parking closing time.
  - Exterior: Boolean to indicate if there is an external area in the car park.
  - HandicapAccess: Boolean to indicate whether there is disabled access.
  - ElectricCharger: Boolean to indicate if there is an electric charging station in the car park.
  - WC: Boolean to indicate if there is a toilet in the car park.
  - Elevator: Boolean to indicate if there is an elevator in the car park.
  - Consigna: Boolean to indicate if there are luggage deposits in the car park.
  - ParkingPriceList: List of parking price entities.
    - Price: List of parking prices.
      - VehicleType: Vehicle type.
      - FractionType: Name of the rate.
      - DescFractionType: Description of the rate.
      - Minutes: Duration of the tariff application in minutes.
      - Amount: Price of the tariff in euros per unit of time.
  - ReferenceRate: Reference rate.
  - Ownership: Owner of the car park.
  - ParkingType: Parking type.

This data provides a complete view of the characteristics and rates of parking in Barcelona, including details on prices, times, access and available services.

https://opendata-ajuntament.barcelona.cat/data/en/dataset/siu-area-blava  
This data represents the forecast of parking space availability in the blue area of Barcelona for two consecutive days.  
Here is a detailed explanation of the fields:

- OPENDATA_PSIU_APPARKB: Array with two properties: "FH_INICIO" and "TRAMOS".
  - FH_INICIO: Start date of the forecasting process in the format dd/mm/yyyy hh24:mi:ss.
  - TRAMOS: Array with a collection of Features in GEOJSON format and of MultiLineString type.
    - type: Type of the trait array.
    - features: Characteristics of the traits.
      - type: Type of the feature.
      - geometry: Geometric characteristics of the stroke.
        - type: Geometry type.
        - coordinates: Array of coordinates (LON, LAT) corresponding to the multilines that make up the section for which seat availability forecasts are provided.
      - properties: Set of JsonObject properties.
        - ID_TRAMO: Identification number of the section.
        - TRAMO: Address of the section.
        - TYPE: Type of section or area. Forecasts are only available for "BLAVA" (blue).
        - TARIFA: Description of the tariff associated with the route.
        - TIMETABLE: Description of the regulated timetable associated with the section.
        - PREDICTIONS: String of 288 numerical digits representing the forecast of seat availability of the section for each of the 5-minute time slots ranging from 08:00 to 20:00 of the current day (144 digits) and of the following day (144 digits) . Forecasts are only available on working days (Monday to Friday). The forecasts are indicated with a numerical figure that can have 4 values:
          - 0: Expected not available (VERDA zones, i.e. green). Represented in grey.
          - 1: Large availability of free places (>80%). Represented in green.
          - 2: Average availability of free places (>30 and <80). Represented in orange.
          - 3: No availability or very low availability (<10). Represented in red.

In [ ]:
#WORK DATA FOR THE ROADS
#if there are works for 2 months on a street in Barcelona then there will certainly be no parking available there in those 2 months
#https://opendata-ajuntament.barcelona.cat/data/en/dataset/est-cadastre-edificacions-any-const

In [ ]:
#for example year 2024

In [3]:
df_constructions_2024 = pd.read_csv('2024_edificacions_any_con.csv')
df_constructions_2024

,Any,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Seccio_censal,Any_construccio,Nombre
0,2024,1,Ciutat Vella,1,el Raval,1,<1901,31
1,2024,1,Ciutat Vella,1,el Raval,2,<1901,58
2,2024,1,Ciutat Vella,1,el Raval,3,<1901,38
3,2024,1,Ciutat Vella,1,el Raval,4,<1901,67
4,2024,1,Ciutat Vella,1,el Raval,5,<1901,90
...,...,...,...,...,...,...,...,...
8262,2024,10,Sant Martí,71,Provençals del Poblenou,94,2021-2030,11
8263,2024,10,Sant Martí,71,Provençals del Poblenou,100,2021-2030,4
8264,2024,10,Sant Martí,71,Provençals del Poblenou,101,2021-2030,8
8265,2024,10,Sant Martí,72,Sant Martí de Provençals,110,2021-2030,1
8266,2024,10,Sant Martí,73,la Verneda i la Pau,138,2021-2030,9

This dataset provides information on the number of cadastral buildings in the city of Barcelona, divided by year of construction. 

- Any: Year of the data.
- Codi_districte: District code.
- Nom_districte: Name of the district.
- Codi_barri: Neighborhood code.
- Nom_barri: Name of the neighborhood.
- Seccio_censal: Census section.
- Any_construccio: Year of construction of the cadastral buildings.
- Nombre: Number of cadastral buildings constructed in the specified year.

Therefore, each row of this dataset represents the number of cadastral buildings built in a specific year, within a specific neighborhood and district of Barcelona. This information can be used to analyze the distribution of buildings over time and space within the city.

In [ ]:
# merge all the data available from 2018 to 2024

In [59]:
file_names = ['2018_edificacions_any_con.csv', '2019_edificacions_any_con.csv', 
              '2020_edificacions_any_con.csv', '2021_edificacions_any_con.csv', 
              '2022_edificacions_any_con.csv', '2023_edificacions_any_con.csv', 
              '2024_edificacions_any_con.csv']

dfs_constructions = []

for file_name in file_names:
    df = pd.read_csv(file_name)
    # Rimuovi le righe con 'NC' nella colonna 'Codi_districte'
    df = df[df['Codi_districte'] != 'NC']
    # Rimuovi le righe con 'NC' nella colonna 'Codi_barri'
    df = df[df['Codi_barri'] != 'NC']
    # Converti le colonne Codi_districte e Codi_barri in interi
    df['Codi_districte'] = df['Codi_districte'].astype(int)
    df['Codi_barri'] = df['Codi_barri'].astype(int)
    dfs_constructions.append(df)

df_constructions = pd.concat(dfs_constructions, ignore_index=True)

In [60]:
df_constructions

,Any,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Seccio_censal,Any_construccio,Nombre
0,2018,1,Ciutat Vella,1,el Raval,1,Abans de 1901,31
1,2018,1,Ciutat Vella,1,el Raval,1,1901 - 1940,10
2,2018,1,Ciutat Vella,1,el Raval,1,1941 - 1950,10
3,2018,1,Ciutat Vella,1,el Raval,1,1951 - 1960,3
4,2018,1,Ciutat Vella,1,el Raval,1,1961 - 1970,4
...,...,...,...,...,...,...,...,...
59028,2024,10,Sant Martí,71,Provençals del Poblenou,94,2021-2030,11
59029,2024,10,Sant Martí,71,Provençals del Poblenou,100,2021-2030,4
59030,2024,10,Sant Martí,71,Provençals del Poblenou,101,2021-2030,8
59031,2024,10,Sant Martí,72,Sant Martí de Provençals,110,2021-2030,1
59032,2024,10,Sant Martí,73,la Verneda i la Pau,138,2021-2030,9

In [98]:
df_constructions.to_csv('df_constructions.csv', index=False)

In [4]:
df_constructions = pd.read_csv('df_constructions.csv')
df_constructions

,Any,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Seccio_censal,Any_construccio,Nombre
0,2018,1,Ciutat Vella,1,el Raval,1,Abans de 1901,31
1,2018,1,Ciutat Vella,1,el Raval,1,1901 - 1940,10
2,2018,1,Ciutat Vella,1,el Raval,1,1941 - 1950,10
3,2018,1,Ciutat Vella,1,el Raval,1,1951 - 1960,3
4,2018,1,Ciutat Vella,1,el Raval,1,1961 - 1970,4
...,...,...,...,...,...,...,...,...
59028,2024,10,Sant Martí,71,Provençals del Poblenou,94,2021-2030,11
59029,2024,10,Sant Martí,71,Provençals del Poblenou,100,2021-2030,4
59030,2024,10,Sant Martí,71,Provençals del Poblenou,101,2021-2030,8
59031,2024,10,Sant Martí,72,Sant Martí de Provençals,110,2021-2030,1
59032,2024,10,Sant Martí,73,la Verneda i la Pau,138,2021-2030,9

- Temporal Analysis of Construction Data:  
Examine how the number of constructions changes over time. Identify periods when there may be construction underway that could affect parking availability in certain areas of the city.

- Spatial correlation:  
Analyzes the distribution of buildings with respect to the areas of the city. You may notice concentrations of construction in certain areas, which may indicate areas of high construction activity.

- Identifying Construction Areas:  
Using construction data, identify streets or census tracts where construction is underway or planned. These areas may experience a reduction in parking availability due to temporary parking restrictions or the presence of construction.

- Integrate into your parking prediction model:  
Once you've identified areas affected by construction, incorporate this information into your parking prediction model. For example, you could consider a variable that indicates the presence of construction in a certain area and how this affects the availability of parking.

- Impact assessment:  
Monitor the effect of construction on parking availability over time. You can compare your model's predictions to actual parking availability data to evaluate the accuracy of the predictions and make any adjustments to the model.

By integrating construction data into your parking prediction project, you will be able to provide more accurate and useful predictions for users looking for parking in Barcelona, taking into account variations due to ongoing construction.

### !!! For the analysis check the file StreetConstructions.ipynb

In [ ]:
#DATA ON AIR QUALITY
#for historical analysis, see pollution trends over the years
#https://opendata-ajuntament.barcelona.cat/data/en/dataset/qualitat-aire-detall-bcn

In [119]:
import glob

file_list = glob.glob('air_quality_data/*.csv')

df_air_quality = pd.DataFrame()

for file in file_list:
    df = pd.read_csv(file)
    df_air_quality = pd.concat([df_air_quality, df])

df_air_quality.reset_index(drop=True, inplace=True)

In [120]:
df_air_quality

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,8,Barcelona,19,Barcelona,4,7,2020,1,1,3.0,...,18.0,V,40.0,V,44.0,V,31.0,V,33.0,V
1,8,Barcelona,19,Barcelona,4,7,2020,1,2,13.0,...,18.0,V,10.0,V,3.0,V,57.0,V,NaN,N
2,8,Barcelona,19,Barcelona,4,7,2020,1,3,33.0,...,56.0,V,46.0,V,40.0,V,32.0,V,NaN,N
3,8,Barcelona,19,Barcelona,4,7,2020,1,4,12.0,...,5.0,V,7.0,V,2.0,V,3.0,V,NaN,N
4,8,Barcelona,19,Barcelona,4,7,2020,1,5,1.0,...,73.0,V,53.0,V,33.0,V,29.0,V,25.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88942,8,Barcelona,19,Barcelona,58,14,2024,3,27,75.0,...,88.0,V,81.0,V,77.0,V,76.0,V,78.0,V
88943,8,Barcelona,19,Barcelona,58,14,2024,3,28,79.0,...,91.0,V,88.0,V,86.0,V,74.0,V,84.0,V
88944,8,Barcelona,19,Barcelona,58,14,2024,3,29,89.0,...,93.0,V,87.0,V,86.0,V,88.0,V,79.0,V
88945,8,Barcelona,19,Barcelona,58,14,2024,3,30,80.0,...,109.0,V,107.0,V,97.0,V,89.0,V,87.0,V
88946,8,Barcelona,19,Barcelona,58,14,2024,3,31,90.0,...,83.0,V,83.0,V,83.0,V,87.0,V,87.0,V

This data represents air quality measurements taken from different monitoring stations in the city of Barcelona. 

- CODI_PROVINCIA, PROVINCE, CODI_MUNICIPI, MUNICIPALI: Code and name of the province and municipality.
- ESTACIO: Air monitoring station code.
- CODI_CONTAMINANT: Code of the contaminant measured.
- ANY, MES, DIA: Year, month and day of the measurement.
- H(nn): Contaminant values measured at the specified time. The value is indicated only if the measurement has been validated (V).
- V(nn): Indicates whether the measurement was validated (V) or not available (N) at the specified time.

The main objective of this dataset is to monitor the levels of contaminants in the air in different areas of Barcelona. Contaminants may include ground-level ozone (O3), nitrogen dioxide (NO2), PM10 particulate matter, among others. Measurements are taken every hour and may or may not be validated.

For example, the line:  
08,Barcelona,019,Barcelona,043,999,2024,4,25,21.4,V,25.3,V,26.3,V,26.4,V,27,V,24.7,V,20.7,V,17.9,V,19, V,18.8,V,19.1,V,17,V,16.9,V,18.9,V,17.4,V,17.4,V,17.2,V,17.1,V,17.7,V,19.3,V,19,V, 17.9,V,20.9,V,21.5,V  
indicates that in the monitoring station with code 043 in Barcelona, on April 25, 2024, measured values (in micrograms per cubic meter or other specified units) for various pollutants were recorded over several hours, and all values were validated (V ).

In [121]:
df_air_quality.to_csv('df_air_quality.csv', index=False)

In [122]:
df_air_quality = pd.read_csv('df_air_quality.csv')
df_air_quality

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,8,Barcelona,19,Barcelona,4,7,2020,1,1,3.0,...,18.0,V,40.0,V,44.0,V,31.0,V,33.0,V
1,8,Barcelona,19,Barcelona,4,7,2020,1,2,13.0,...,18.0,V,10.0,V,3.0,V,57.0,V,NaN,N
2,8,Barcelona,19,Barcelona,4,7,2020,1,3,33.0,...,56.0,V,46.0,V,40.0,V,32.0,V,NaN,N
3,8,Barcelona,19,Barcelona,4,7,2020,1,4,12.0,...,5.0,V,7.0,V,2.0,V,3.0,V,NaN,N
4,8,Barcelona,19,Barcelona,4,7,2020,1,5,1.0,...,73.0,V,53.0,V,33.0,V,29.0,V,25.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88942,8,Barcelona,19,Barcelona,58,14,2024,3,27,75.0,...,88.0,V,81.0,V,77.0,V,76.0,V,78.0,V
88943,8,Barcelona,19,Barcelona,58,14,2024,3,28,79.0,...,91.0,V,88.0,V,86.0,V,74.0,V,84.0,V
88944,8,Barcelona,19,Barcelona,58,14,2024,3,29,89.0,...,93.0,V,87.0,V,86.0,V,88.0,V,79.0,V
88945,8,Barcelona,19,Barcelona,58,14,2024,3,30,80.0,...,109.0,V,107.0,V,97.0,V,89.0,V,87.0,V
88946,8,Barcelona,19,Barcelona,58,14,2024,3,31,90.0,...,83.0,V,83.0,V,83.0,V,87.0,V,87.0,V

### !!! For the analysis check the file AirQuality.ipynb

In [ ]:
#DATA ON EVENTS IN BARCELONA
#events require parking
#https://opendata-ajuntament.barcelona.cat/data/en/dataset/agenda-diaria

In [4]:
df_air_events = pd.read_csv('opendatabcn_agenda-csv.csv', encoding='latin-1')
df_air_events

ParserError: Error tokenizing data. C error: Expected 39 fields in line 37, saw 40

This dataset appears to be a list of events and activities in the city of Barcelona. Each row represents a single event or activity and contains various information about it, such as name, location, start and end dates, description, and other related information.

- register_id: A unique identifier for each event.
- name: The name of the event or activity.
- institution_id and institution_name: identifier and name of the institution associated with the event, if present.
- created and modified: date of creation and last modification of the event in the dataset.
- addresses_roadtype_id, addresses_roadtype_name, addresses_road_id, addresses_road_name, addresses_start_street_number, addresses_end_street_number, addresses_neighborhood_id, addresses_neighborhood_name, addresses_district_id, addresses_district_name, addresses_zip_code, addresses_town, addresses_main_address, addresses_type: Event address information.
- start_date and end_date: start and end date of the event.
- Other columns such as body (event description), values (attributes), secondary_filters, and so on, provide additional details about the event or activity.

This dataset could be used to analyze events taking place in Barcelona, for example to create calendars, analyze the frequency of certain types of events in certain areas of the city or for other analyzes related to cultural events and activities.